name: fudiko
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^2.17.1
  flutter: ^3.0.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_riverpod:
  http:
  freezed_annotation:
  xml:
  intl:
  collection:
  cached_network_image:
  just_audio:
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  freezed:

flutter:
  uses-material-design: true