name: razio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  audio_service: ^0.18.7
  blur: ^4.0.0
  build_runner: ^2.3.2
  cached_network_image: ^3.2.3
  clickable_list_wheel_view: ^0.2.0
  collection: ^1.16.0
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.1.0+1
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.2
  freezed_annotation: ^2.2.0
  go_router: ^14.3.0
  hooks_riverpod: ^2.1.3
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.0
  json_serializable: ^6.5.4
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.8
  pedantic_mono: ^1.20.0
  simple_logger: ^1.9.0+1
  simple_shadow: ^0.3.0
  xml: ^6.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/images/
  fonts:
    - family: LINESeed
      fonts:
        - asset: assets/fonts/LINESeedJP_A_OTF_Th.otf
          weight: 100
        - asset: assets/fonts/LINESeedJP_A_OTF_Rg.otf
          weight: 400
        - asset: assets/fonts/LINESeedJP_A_OTF_Bd.otf
          weight: 700
        - asset: assets/fonts/LINESeedJP_A_OTF_Eb.otf
          weight: 800
  uses-material-design: true